// src/js/components/VisComponent.svelte
<script>
  import { beforeUpdate } from 'svelte';
  import { scaleLinear, extent } from 'd3';

  import VisComponentElement from './VisComponentElement.svelte';

  export let data = [];

  let xScale = d => d;
  let yScale = d => d;

  beforeUpdate(() => {
    if (data.length > 0) {
      const newXScale = scaleLinear()
        .domain(extent(data, d => d.x))
        .range([10, 290]);
      const newYScale = scaleLinear()
        .domain(extent(data, d => d.y))
        .range([10, 140]);
      xScale = newXScale;
      yScale = newYScale;
    }
  });

  $: console.log(data);
</script>

<div>
  <p>Vis: {data.length}</p>
  <svg id="viz">
    {#each data as d (d.id)}
      <VisComponentElement data={d} {xScale} {yScale} />
    {/each}
  </svg>
</div>

// src/jsx/components/VisComponent.jsx
import React from 'react';
import { observer } from 'mobx-react';
import { scaleLinear, extent } from 'd3';

import VisComponentElement from './VisComponentElement';

@observer
export default class VisComponent extends React.Component {
  constructor() {
    super();
    this.state = VisComponent.getDefaultScales();
  }

  static getDefaultScales() {
    return {
      xScale: d => d,
      yScale: d => d,
    };
  }

  static getDerivedStateFromProps(props, state) {
    if (props.data && props.data.length > 0) {
      const xScale = scaleLinear()
        .domain(extent(props.data, d => d.x))
        .range([10, 290]);
      const yScale = scaleLinear()
        .domain(extent(props.data, d => d.y))
        .range([10, 140]);
      return {
        xScale,
        yScale,
      };
    }

    return VisComponent.getDefaultScales();
  }

  render() {
    const { data } = this.props;
    const els = data.map(d => (
      <VisComponentElement
        key={d.id}
        data={d}
        xScale={this.state.xScale}
        yScale={this.state.yScale}
      />
    ));
    return (
      <div>
        <p>Vis: {data.length} items</p>
        <svg id="viz">{els}</svg>
      </div>
    );
  }
}
