// src/js/App.svelte
<script>
  import { items, ready } from './data/dataAPI.js';
  import VisComponent from './components/VisComponent.svelte';

  import { hoveredItemId } from './state/uiStore.js';
</script>

<div>
  <h1>Äpp</h1>
  {#if ready}
    <div>
      <VisComponent data={$items} />
      {#if $hoveredItemId}
        <p> {`Hovering over ${$hoveredItemId}`} </p>
      {/if}
    </div>
  {:else}
    <div>Loading...</div>
  {/if}
</div>

// src/jsx/App.jsx
/* eslint-disable no-console */

import React, { Component } from 'react';

import { observer } from 'mobx-react';

import uiState from './state/uiState';

import dataAPI from './data/dataAPI';

import VisComponent from './components/VisComponent';

@observer
class App extends Component {
  constructor() {
    super();
  }

  render() {
    console.log('App.render', dataAPI.items);
    const { items } = dataAPI;
    return (
      <div>
        <h1>Currentview: {uiState.currentView}</h1>

        {dataAPI.ready && (
          <div>
            <h2>Data loaded — {items.length} items</h2>
            <VisComponent data={dataAPI.items} />
          </div>
        )}
      </div>
    );
  }
}

export default App;
